import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] }) //police d'écritures ?

export const metadata = { //métadonnées du site, pour SEO
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>{children}      
      </body>
    </html>
  )
}
